version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: weather_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/weather_api
      - REDIS_URL=redis://redis:6379/1
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY:-}

  celery:
    build: .
    command: celery -A weather_project worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/weather_api
      - REDIS_URL=redis://redis:6379/1
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY:-}

volumes:
  postgres_data: 