# Generated by Django 4.2.7 on 2025-06-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('country', models.CharField(max_length=2, verbose_name='País')),
                ('temperature', models.FloatField(verbose_name='Temperatura (°C)')),
                ('feels_like', models.FloatField(verbose_name='Sensação Térmica (°C)')),
                ('humidity', models.IntegerField(verbose_name='Umidade (%)')),
                ('pressure', models.IntegerField(verbose_name='Pressão (hPa)')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='Ícone')),
                ('wind_speed', models.FloatField(default=0, verbose_name='Velocidade do Vento (m/s)')),
                ('wind_direction', models.IntegerField(default=0, verbose_name='Direção do Vento (graus)')),
                ('visibility', models.IntegerField(default=0, verbose_name='Visibilidade (m)')),
                ('uv_index', models.FloatField(default=0, verbose_name='Índice UV')),
                ('query_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da Consulta')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP do Solicitante')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Consulta Meteorológica',
                'verbose_name_plural': 'Consultas Meteorológicas',
                'ordering': ['-query_timestamp'],
                'indexes': [models.Index(fields=['-query_timestamp'], name='weather_wea_query_t_ed96e8_idx'), models.Index(fields=['city'], name='weather_wea_city_d848c9_idx')],
            },
        ),
    ]
